name: Reusable Docker CI

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }} .

      # Trivy Scan
      - name: Scan Image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Slack Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Image built & pushed successfully"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Pipeline failed (build/scan/push)"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}